In [1]:
import pandas as pd

file_path = "/content/Online Retail.xlsx"

df = pd.read_excel(file_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 541909
Columns: 8

In [2]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [4]:
df.shape

(541909, 8)

In [5]:
# Check the dataset dimensions
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

# Display column names
print("\nColumn names:")
print(df.columns.tolist())

# Check missing values
print("\nMissing values:")
print(df.isnull().sum())

# Check duplicate rows
print("\nNumber of duplicate rows:")
print(df.duplicated().sum())

# Check basic statistics for numerical columns
print("\nNumerical summary:")
display(df.describe())

# Check data types
print("\nData types:")
print(df.dtypes)

Number of rows: 541909
Number of columns: 8

Column names:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

Missing values:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Number of duplicate rows:
5268

Numerical summary:

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

Data types:
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [6]:
# Check unusual values in Quantity and UnitPrice

print("Quantity <= 0:", (df["Quantity"] <= 0).sum())
print("UnitPrice <= 0:", (df["UnitPrice"] <= 0).sum())

print("\nLowest quantities:")
display(df.nsmallest(10, "Quantity")[["InvoiceNo", "StockCode", "Quantity"]])

print("\nLowest unit prices:")
display(df.nsmallest(10, "UnitPrice")[["InvoiceNo", "StockCode", "UnitPrice"]])

Quantity <= 0: 10624
UnitPrice <= 0: 2517

Lowest quantities:

       InvoiceNo StockCode  Quantity
540422   C581484     23843    -80995
61624    C541433     23166    -74215
225529    556690     23005     -9600
225530    556691     23005     -9600
4287     C536757     84347     -9360
225528    556687     23003     -9058
115818    546152    72140F     -5368
431381    573596    79323W     -4830
341601    566768     16045     -3667
323458    565304     16259     -3167

Lowest unit prices:

       InvoiceNo StockCode  UnitPrice
299983   A563186         B  -11062.06
299984   A563187         B  -11062.06
622       536414     22139       0.00
1970      536545     21134       0.00
1971      536546     22145       0.00
1972      536547     37509       0.00
1987      536549    85226A       0.00
1988      536550     85044       0.00
2024      536552     20950       0.00
2025      536553     37461       0.00

In [7]:
negative_quantity = df[df["Quantity"] < 0]

print("Negative quantity records:", len(negative_quantity))

print("\nDo negative quantities have cancelled invoices?")
print(
    negative_quantity["InvoiceNo"]
    .astype(str)
    .str.startswith("C")
    .value_counts()
)

print("\nSample negative quantity records:")
display(
    negative_quantity[
        ["InvoiceNo", "StockCode", "Description", "Quantity",
         "InvoiceDate", "UnitPrice", "CustomerID", "Country"]
    ].head(20)
)

Negative quantity records: 10624

Do negative quantities have cancelled invoices?
InvoiceNo
True     9288
False    1336
Name: count, dtype: int64

Sample negative quantity records:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,2010-12-01 14:33:00,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,2010-12-01 14:33:00,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2010-12-01 14:33:00,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,2010-12-01 14:33:00,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,2010-12-01 14:33:00,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,2010-12-01 14:33:00,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,2010-12-01 14:33:00,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,2010-12-01 14:33:00,0.85,12472.0,Germany

In [8]:
non_positive_price = df[df["UnitPrice"] <= 0]

print("Records with UnitPrice <= 0:", len(non_positive_price))

print("\nNegative UnitPrice records:")
display(
    df[df["UnitPrice"] < 0][
        ["InvoiceNo", "StockCode", "Description",
         "Quantity", "UnitPrice", "CustomerID", "Country"]
    ]
)

print("\nZero UnitPrice records:")
display(
    df[df["UnitPrice"] == 0][
        ["InvoiceNo", "StockCode", "Description",
         "Quantity", "UnitPrice", "CustomerID", "Country"]
    ].head(20)
)

Records with UnitPrice <= 0: 2517

Negative UnitPrice records:

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,-11062.06,NaN,United Kingdom

Zero UnitPrice records:

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,0.0,NaN,United Kingdom
6391,536941,22734,amazon,20,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,0.0,NaN,United Kingdom

In [9]:
duplicate_count = df.duplicated().sum()

print("Total duplicate rows:", duplicate_count)

display(
    df[df.duplicated(keep=False)]
    .sort_values(by=["InvoiceNo", "StockCode"])
    .head(20)
)

Total duplicate rows: 5268

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom

In [10]:
missing = df.isnull().sum()
missing_percentage = (missing / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing Values": missing,
    "Missing Percentage": missing_percentage.round(2)
})

display(missing_summary)

             Missing Values  Missing Percentage
InvoiceNo                 0                0.00
StockCode                 0                0.00
Description            1454                0.27
Quantity                  0                0.00
InvoiceDate               0                0.00
UnitPrice                 0                0.00
CustomerID           135080               24.93
Country                   0                0.00

In [11]:
negative_non_cancelled = df[
    (df["Quantity"] < 0) &
    (~df["InvoiceNo"].astype(str).str.startswith("C"))
]

print("Negative quantity records without 'C':", len(negative_non_cancelled))

display(
    negative_non_cancelled[
        ["InvoiceNo", "StockCode", "Description", "Quantity",
         "InvoiceDate", "UnitPrice", "CustomerID", "Country"]
    ].head(30)
)

Negative quantity records without 'C': 1336

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,2010-12-03 15:39:00,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7208,537016,21836,NaN,-15,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7209,537017,47556B,NaN,-69,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7210,537018,84562A,NaN,-3,2010-12-03 15:42:00,0.0,NaN,United Kingdom
7211,537019,37474,NaN,-15,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7212,537020,21807,NaN,-30,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7213,537021,21011,NaN,-20,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7291,537027,18098C,NaN,-140,2010-12-03 16:36:00,0.0,NaN,United Kingdom
7292,537028,21696,NaN,-320,2010-12-03 16:36:00,0.0,NaN,United Kingdom
7293,537029,37476,NaN,-6,2010-12-03 16:37:00,0.0,NaN,United Kingdom
7313,537032,21275,?,-30,2010-12-03 16:50:00,0.0,NaN,United Kingdom

In [12]:
missing = df.isnull().sum()
missing_percentage = (missing / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing Values": missing,
    "Missing Percentage": missing_percentage.round(2)
})

display(missing_summary)

             Missing Values  Missing Percentage
InvoiceNo                 0                0.00
StockCode                 0                0.00
Description            1454                0.27
Quantity                  0                0.00
InvoiceDate               0                0.00
UnitPrice                 0                0.00
CustomerID           135080               24.93
Country                   0                0.00

In [13]:
# Examine rows with missing Description
missing_description = df[df['Description'].isna()]

print("Rows with missing Description:", len(missing_description))
display(missing_description.head(20))

Rows with missing Description: 1454

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7194,537002,21651,NaN,70,2010-12-03 15:33:00,0.0,NaN,United Kingdom

In [14]:
# Examine rows with missing CustomerID
missing_customer = df[df['CustomerID'].isna()]

print("Rows with missing CustomerID:", len(missing_customer))
display(missing_customer.head(20))

Rows with missing CustomerID: 135080

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1448,536544,21791,VINTAGE HEADS AND TAILS CARD GAME,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1449,536544,21801,CHRISTMAS TREE DECORATION WITH BELL,10,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1450,536544,21802,CHRISTMAS TREE HEART DECORATION,9,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1451,536544,21803,CHRISTMAS TREE STAR DECORATION,11,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1452,536544,21809,CHRISTMAS HANGING TREE WITH BELL,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1453,536544,21810,CHRISTMAS HANGING STAR WITH BELL,3,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1454,536544,21811,CHRISTMAS HANGING HEART WITH BELL,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1455,536544,21821,GLITTER STAR GARLAND WITH BELLS,1,2010-12-01 14:32:00,7.62,NaN,United Kingdom
1456,536544,21822,GLITTER CHRISTMAS TREE WITH BELLS,1,2010-12-01 14:32:00,4.21,NaN,United Kingdom
1457,536544,21823,PAINTED METAL HEART WITH HOLLY BELL,2,2010-12-01 14:32:00,2.98,NaN,United Kingdom
1458,536544,21844,RED RETROSPOT MUG,2,2010-12-01 14:32:00,5.91,NaN,United Kingdom
1459,536544,21851,LILAC DIAMANTE PEN IN GIFT BOX,1,2010-12-01 14:32:00,4.21,NaN,United Kingdom
1460,536544,21870,I CAN ONLY PLEASE ONE PERSON MUG,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1461,536544,21871,SAVE THE PLANET MUG,5,2010-12-01 14:32:00,3.36,NaN,United Kingdom

In [15]:
# Examine rows with missing CustomerID
missing_customer = df[df['CustomerID'].isna()]

print("Rows with missing CustomerID:", len(missing_customer))

display(missing_customer.head(20))

Rows with missing CustomerID: 135080

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1448,536544,21791,VINTAGE HEADS AND TAILS CARD GAME,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1449,536544,21801,CHRISTMAS TREE DECORATION WITH BELL,10,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1450,536544,21802,CHRISTMAS TREE HEART DECORATION,9,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1451,536544,21803,CHRISTMAS TREE STAR DECORATION,11,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1452,536544,21809,CHRISTMAS HANGING TREE WITH BELL,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1453,536544,21810,CHRISTMAS HANGING STAR WITH BELL,3,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1454,536544,21811,CHRISTMAS HANGING HEART WITH BELL,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1455,536544,21821,GLITTER STAR GARLAND WITH BELLS,1,2010-12-01 14:32:00,7.62,NaN,United Kingdom
1456,536544,21822,GLITTER CHRISTMAS TREE WITH BELLS,1,2010-12-01 14:32:00,4.21,NaN,United Kingdom
1457,536544,21823,PAINTED METAL HEART WITH HOLLY BELL,2,2010-12-01 14:32:00,2.98,NaN,United Kingdom
1458,536544,21844,RED RETROSPOT MUG,2,2010-12-01 14:32:00,5.91,NaN,United Kingdom
1459,536544,21851,LILAC DIAMANTE PEN IN GIFT BOX,1,2010-12-01 14:32:00,4.21,NaN,United Kingdom
1460,536544,21870,I CAN ONLY PLEASE ONE PERSON MUG,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1461,536544,21871,SAVE THE PLANET MUG,5,2010-12-01 14:32:00,3.36,NaN,United Kingdom

In [16]:
# Check whether missing CustomerID records have zero prices
print("Missing CustomerID + UnitPrice = 0:",
      ((df['CustomerID'].isna()) & (df['UnitPrice'] == 0)).sum())

# Check whether missing CustomerID records have negative quantities
print("Missing CustomerID + negative Quantity:",
      ((df['CustomerID'].isna()) & (df['Quantity'] < 0)).sum())

Missing CustomerID + UnitPrice = 0: 2475
Missing CustomerID + negative Quantity: 1719

In [17]:
# Examine duplicate records
duplicates = df[df.duplicated(keep=False)]

print("Total duplicate records:", len(duplicates))

display(duplicates.sort_values(
    by=['InvoiceNo', 'StockCode']
).head(20))

Total duplicate records: 10147

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom

In [18]:
# Count exact duplicate rows
exact_duplicates = df[df.duplicated(keep='first')]

print("Exact duplicate rows to remove:", len(exact_duplicates))

# Show a few exact duplicate groups
display(
    df[df.duplicated(keep=False)]
    .sort_values(by=["InvoiceNo", "StockCode", "Quantity"])
    .head(30)
)

Exact duplicate rows to remove: 5268

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
597,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
569,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
611,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
617,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
603,536412,22902,TOTE BAG I LOVE LONDON,7,2010-12-01 11:49:00,2.10,17920.0,United Kingdom

In [19]:
# Create a copy of the original dataset
clean_df = df.copy()

# Remove exact duplicate rows
clean_df = clean_df.drop_duplicates()

print("Original rows:", len(df))
print("Rows after removing duplicates:", len(clean_df))
print("Rows removed:", len(df) - len(clean_df))

Original rows: 541909
Rows after removing duplicates: 536641
Rows removed: 5268

In [20]:
# Check negative quantities after removing duplicates
negative_qty = clean_df[clean_df["Quantity"] < 0]

print("Negative quantity records:", len(negative_qty))

# Check how many have cancellation invoice numbers
has_cancel_invoice = negative_qty["InvoiceNo"].astype(str).str.startswith("C")

print("\nNegative quantity records with cancellation invoices:")
print(has_cancel_invoice.value_counts())

Negative quantity records: 10587

Negative quantity records with cancellation invoices:
InvoiceNo
True     9251
False    1336
Name: count, dtype: int64

In [21]:
# Negative quantities without a cancellation invoice
unusual_negative = clean_df[
    (clean_df["Quantity"] < 0) &
    (~clean_df["InvoiceNo"].astype(str).str.startswith("C"))
]

print("Negative quantity records without cancellation invoice:",
      len(unusual_negative))

display(unusual_negative.head(20))

Negative quantity records without cancellation invoice: 1336

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,2010-12-03 15:39:00,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,2010-12-03 15:41:00,0.0,NaN,United Kingdom

In [22]:
# Check whether all unusual negative records have zero UnitPrice
print("UnitPrice = 0:",
      (unusual_negative["UnitPrice"] == 0).sum())

print("UnitPrice > 0:",
      (unusual_negative["UnitPrice"] > 0).sum())

print("UnitPrice < 0:",
      (unusual_negative["UnitPrice"] < 0).sum())

print("\nMissing Description:",
      unusual_negative["Description"].isna().sum())

print("Missing CustomerID:",
      unusual_negative["CustomerID"].isna().sum())

UnitPrice = 0: 1336
UnitPrice > 0: 0
UnitPrice < 0: 0

Missing Description: 862
Missing CustomerID: 1336

In [23]:
# Remove negative-quantity records that are not cancellation invoices
clean_df = clean_df[
    ~(
        (clean_df["Quantity"] < 0) &
        (~clean_df["InvoiceNo"].astype(str).str.startswith("C"))
    )
].copy()

print("Rows after removing non-standard negative records:", len(clean_df))

Rows after removing non-standard negative records: 535305

In [24]:
# Check zero UnitPrice records in the current cleaned dataset
zero_price = clean_df[clean_df["UnitPrice"] == 0]

print("Zero UnitPrice records:", len(zero_price))

print("\nMissing Description:",
      zero_price["Description"].isna().sum())

print("Missing CustomerID:",
      zero_price["CustomerID"].isna().sum())

print("\nQuantity <= 0:",
      (zero_price["Quantity"] <= 0).sum())

print("Quantity > 0:",
      (zero_price["Quantity"] > 0).sum())

Zero UnitPrice records: 1174

Missing Description: 592
Missing CustomerID: 1134

Quantity <= 0: 0
Quantity > 0: 1174

In [25]:
# Inspect descriptions of zero-price records
zero_price_desc = (
    zero_price["Description"]
    .value_counts(dropna=False)
)

print("Number of unique descriptions:", zero_price_desc.shape[0])

display(zero_price_desc.head(30))

Number of unique descriptions: 247

Description
NaN                                  592
check                                 39
found                                 25
adjustment                            14
FRENCH BLUE METAL DOOR SIGN 1          9
FRENCH BLUE METAL DOOR SIGN 8          8
amazon                                 8
Found                                  8
FRENCH BLUE METAL DOOR SIGN 3          7
RECIPE BOX PANTRY YELLOW DESIGN        7
OWL DOORSTOP                           7
FRENCH BLUE METAL DOOR SIGN 4          7
Amazon                                 7
FRENCH BLUE METAL DOOR SIGN No         7
RED KITCHEN SCALES                     6
?                                      6
FRENCH BLUE METAL DOOR SIGN 6          6
FRENCH BLUE METAL DOOR SIGN 5          6
FRENCH BLUE METAL DOOR SIGN 7          6
Manual                                 6
FRENCH BLUE METAL DOOR SIGN 2          5
FRENCH BLUE METAL DOOR SIGN 9          5
RED RETROSPOT CHARLOTTE BAG            5
MINT KITCHEN SCALES                    5
RECIPE BOX BLUE SKETCHBOOK DESIGN      5
POLYESTER FILLER PAD 45x45cm           5
had been put aside                     5
BOX OF 24 COCKTAIL PARASOLS            5
IVORY KITCHEN SCALES                   5
CHILDS GARDEN SPADE BLUE               5
Name: count, dtype: int64

In [26]:
# Check negative UnitPrice records
negative_price = clean_df[clean_df["UnitPrice"] < 0]

print("Negative UnitPrice records:", len(negative_price))

display(negative_price)

Negative UnitPrice records: 2

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [27]:
# Remove negative UnitPrice accounting adjustment records
clean_df = clean_df[clean_df["UnitPrice"] >= 0].copy()

print("Rows after removing negative-price adjustments:", len(clean_df))

Rows after removing negative-price adjustments: 535303

In [28]:
# Check missing values in the current cleaned dataset
missing_values = clean_df.isnull().sum()

missing_percent = (missing_values / len(clean_df)) * 100

missing_summary = pd.DataFrame({
    "Missing Values": missing_values,
    "Percentage": missing_percent.round(2)
})

display(missing_summary)

             Missing Values  Percentage
InvoiceNo                 0        0.00
StockCode                 0        0.00
Description             592        0.11
Quantity                  0        0.00
InvoiceDate               0        0.00
UnitPrice                 0        0.00
CustomerID           133699       24.98
Country                   0        0.00

In [29]:
# Calculate IQR-based outlier bounds for Quantity and UnitPrice

Q1_quantity = clean_df["Quantity"].quantile(0.25)
Q3_quantity = clean_df["Quantity"].quantile(0.75)
IQR_quantity = Q3_quantity - Q1_quantity

lower_quantity = Q1_quantity - 1.5 * IQR_quantity
upper_quantity = Q3_quantity + 1.5 * IQR_quantity

Q1_price = clean_df["UnitPrice"].quantile(0.25)
Q3_price = clean_df["UnitPrice"].quantile(0.75)
IQR_price = Q3_price - Q1_price

lower_price = Q1_price - 1.5 * IQR_price
upper_price = Q3_price + 1.5 * IQR_price

print("Quantity IQR bounds:", lower_quantity, "to", upper_quantity)
print("UnitPrice IQR bounds:", lower_price, "to", upper_price)

print("\nQuantity outliers:",
      ((clean_df["Quantity"] < lower_quantity) |
       (clean_df["Quantity"] > upper_quantity)).sum())

print("UnitPrice outliers:",
      ((clean_df["UnitPrice"] < lower_price) |
       (clean_df["UnitPrice"] > upper_price)).sum())

Quantity IQR bounds: -12.5 to 23.5
UnitPrice IQR bounds: -3.0700000000000003 to 8.45

Quantity outliers: 57598
UnitPrice outliers: 39448

In [30]:
# Inspect the largest Quantity values
print("Top 20 highest Quantity values:")
display(
    clean_df.nlargest(20, "Quantity")[
        ["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "CustomerID", "Country"]
    ]
)

# Inspect the highest UnitPrice values
print("\nTop 20 highest UnitPrice values:")
display(
    clean_df.nlargest(20, "UnitPrice")[
        ["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "CustomerID", "Country"]
    ]
)

Top 20 highest Quantity values:

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,16446.0,United Kingdom
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,12346.0,United Kingdom
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,0.00,13256.0,United Kingdom
74614,542504,37413,NaN,5568,0.00,NaN,United Kingdom
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,0.21,12901.0,United Kingdom
206121,554868,22197,SMALL POPCORN HOLDER,4300,0.72,13135.0,United Kingdom
220843,556231,85123A,?,4000,0.00,NaN,United Kingdom
97432,544612,22053,EMPIRE DESIGN ROSETTE,3906,0.82,18087.0,United Kingdom
270885,560599,18007,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,3186,0.06,14609.0,United Kingdom
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,15749.0,United Kingdom
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,15749.0,United Kingdom
263885,560040,23343,came coded as 20713,3100,0.00,NaN,United Kingdom
115807,546139,84988,?,3000,0.00,NaN,United Kingdom
433788,573995,16014,SMALL CHINESE STYLE SCISSOR,3000,0.32,16308.0,United Kingdom
4945,536830,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2880,0.18,16754.0,United Kingdom
291249,562439,84879,ASSORTED COLOUR BIRD ORNAMENT,2880,1.45,12931.0,United Kingdom
201149,554272,21977,PACK OF 60 PINK PAISLEY CAKE CASES,2700,0.42,12901.0,United Kingdom
80742,543057,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2592,0.21,16333.0,United Kingdom
74615,542505,79063D,NaN,2560,0.00,NaN,United Kingdom
32671,539101,22693,GROW A FLYTRAP OR SUNFLOWER IN TIN,2400,0.94,16029.0,United Kingdom

Top 20 highest UnitPrice values:

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
222681,C556445,M,Manual,-1,38970.00,15098.0,United Kingdom
524602,C580605,AMAZONFEE,AMAZON FEE,-1,17836.46,NaN,United Kingdom
43702,C540117,AMAZONFEE,AMAZON FEE,-1,16888.02,NaN,United Kingdom
43703,C540118,AMAZONFEE,AMAZON FEE,-1,16453.71,NaN,United Kingdom
15016,C537630,AMAZONFEE,AMAZON FEE,-1,13541.33,NaN,United Kingdom
15017,537632,AMAZONFEE,AMAZON FEE,1,13541.33,NaN,United Kingdom
16356,C537651,AMAZONFEE,AMAZON FEE,-1,13541.33,NaN,United Kingdom
16232,C537644,AMAZONFEE,AMAZON FEE,-1,13474.79,NaN,United Kingdom
524601,C580604,AMAZONFEE,AMAZON FEE,-1,11586.50,NaN,United Kingdom
299982,A563185,B,Adjust bad debt,1,11062.06,NaN,United Kingdom
446533,C574902,AMAZONFEE,AMAZON FEE,-1,8286.22,NaN,United Kingdom
173277,C551685,POST,POSTAGE,-1,8142.75,16029.0,United Kingdom
173382,551697,POST,POSTAGE,1,8142.75,16029.0,United Kingdom
342635,C566899,AMAZONFEE,AMAZON FEE,-1,7427.97,NaN,United Kingdom
191386,C553355,AMAZONFEE,AMAZON FEE,-1,7006.83,NaN,United Kingdom
173391,C551699,M,Manual,-1,6930.00,16029.0,United Kingdom
287150,C562086,AMAZONFEE,AMAZON FEE,-1,6721.37,NaN,United Kingdom
16357,C537652,AMAZONFEE,AMAZON FEE,-1,6706.71,NaN,United Kingdom
312246,C564341,AMAZONFEE,AMAZON FEE,-1,6662.51,NaN,United Kingdom
262414,C559917,AMAZONFEE,AMAZON FEE,-1,6497.47,NaN,United Kingdom

In [31]:
# Check unusual/non-product descriptions among high UnitPrice records

unusual_keywords = [
    "AMAZON",
    "POSTAGE",
    "MANUAL",
    "ADJUST",
    "BAD DEBT",
    "FEE"
]

pattern = "|".join(unusual_keywords)

unusual_records = clean_df[
    clean_df["Description"].astype(str).str.upper().str.contains(
        pattern, na=False
    )
]

print("Number of unusual/non-product records:", len(unusual_records))

display(
    unusual_records[
        ["InvoiceNo", "StockCode", "Description",
         "Quantity", "UnitPrice", "CustomerID", "Country"]
    ].sort_values("UnitPrice", ascending=False).head(30)
)

Number of unusual/non-product records: 6165

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
222681,C556445,M,Manual,-1,38970.00,15098.0,United Kingdom
524602,C580605,AMAZONFEE,AMAZON FEE,-1,17836.46,NaN,United Kingdom
43702,C540117,AMAZONFEE,AMAZON FEE,-1,16888.02,NaN,United Kingdom
43703,C540118,AMAZONFEE,AMAZON FEE,-1,16453.71,NaN,United Kingdom
15017,537632,AMAZONFEE,AMAZON FEE,1,13541.33,NaN,United Kingdom
16356,C537651,AMAZONFEE,AMAZON FEE,-1,13541.33,NaN,United Kingdom
15016,C537630,AMAZONFEE,AMAZON FEE,-1,13541.33,NaN,United Kingdom
16232,C537644,AMAZONFEE,AMAZON FEE,-1,13474.79,NaN,United Kingdom
524601,C580604,AMAZONFEE,AMAZON FEE,-1,11586.50,NaN,United Kingdom
299982,A563185,B,Adjust bad debt,1,11062.06,NaN,United Kingdom
446533,C574902,AMAZONFEE,AMAZON FEE,-1,8286.22,NaN,United Kingdom
173382,551697,POST,POSTAGE,1,8142.75,16029.0,United Kingdom
173277,C551685,POST,POSTAGE,-1,8142.75,16029.0,United Kingdom
342635,C566899,AMAZONFEE,AMAZON FEE,-1,7427.97,NaN,United Kingdom
191386,C553355,AMAZONFEE,AMAZON FEE,-1,7006.83,NaN,United Kingdom
173391,C551699,M,Manual,-1,6930.00,16029.0,United Kingdom
287150,C562086,AMAZONFEE,AMAZON FEE,-1,6721.37,NaN,United Kingdom
16357,C537652,AMAZONFEE,AMAZON FEE,-1,6706.71,NaN,United Kingdom
312246,C564341,AMAZONFEE,AMAZON FEE,-1,6662.51,NaN,United Kingdom
262414,C559917,AMAZONFEE,AMAZON FEE,-1,6497.47,NaN,United Kingdom
429248,C573549,AMAZONFEE,AMAZON FEE,-1,5942.57,NaN,United Kingdom
383495,C570025,AMAZONFEE,AMAZON FEE,-1,5942.57,NaN,United Kingdom
446434,C574897,AMAZONFEE,AMAZON FEE,-1,5877.18,NaN,United Kingdom
191385,C553354,AMAZONFEE,AMAZON FEE,-1,5876.40,NaN,United Kingdom
239250,C558036,AMAZONFEE,AMAZON FEE,-1,5791.18,NaN,United Kingdom
124741,C546987,AMAZONFEE,AMAZON FEE,-1,5693.05,NaN,United Kingdom
96844,C544587,AMAZONFEE,AMAZON FEE,-1,5575.28,NaN,United Kingdom
342611,C566889,AMAZONFEE,AMAZON FEE,-1,5522.14,NaN,United Kingdom
16313,C537647,AMAZONFEE,AMAZON FEE,-1,5519.25,NaN,United Kingdom
96845,C544589,AMAZONFEE,AMAZON FEE,-1,5258.77,NaN,United Kingdom

In [32]:
# Count the unusual/non-product records by description

print(
    unusual_records["Description"]
    .value_counts(dropna=False)
    .head(30)
)

Description
POSTAGE                                1252
DOTCOM POSTAGE                          709
Manual                                  567
SET OF TEA COFFEE SUGAR TINS PANTRY     506
SET 3 RETROSPOT TEA,COFFEE,SUGAR        444
LONDON BUS COFFEE MUG                   322
QUEENS GUARD COFFEE MUG                 279
COFFEE MUG APPLES DESIGN                272
COFFEE MUG CAT + BIRD DESIGN            266
COFFEE MUG PEARS  DESIGN                216
COFFEE MUG DOG + BALL DESIGN            202
RETRO COFFEE MUGS ASSORTED              167
POLKADOT COFFEE CUP & SAUCER PINK       113
ENAMEL PINK COFFEE CONTAINER             76
BLUE POLKADOT COFFEE MUG                 75
BAKING MOULD TOFFEE CUP CHOCOLATE        73
WHITE TEA,COFFEE,SUGAR JARS              72
RED POLKADOT COFFEE  MUG                 63
COFFEE SCENT PILLAR CANDLE               62
COFFEE MUG BLUE PAISLEY DESIGN           61
BLACK TEA,COFFEE,SUGAR JARS              53
COFFEE MUG PINK PAISLEY DESIGN           52
AMAZON FEE                               34
KENSINGTON COFFEE SET                    34
VINTAGE COFFEE GRINDER BOX               31
ENAMEL BLUE RIM COFFEE CONTAINER         28
VINTAGE GLASS COFFEE CADDY               26
TUSCAN VILLA DOVECOTE BIRD FEEDER        24
DECORATIVE VINTAGE COFFEE  BOX           22
adjustment                               14
Name: count, dtype: int64

In [33]:
# Count clearly non-product transaction types

non_product = clean_df[
    clean_df["Description"].astype(str).str.upper().isin([
        "POSTAGE",
        "DOTCOM POSTAGE",
        "MANUAL",
        "AMAZON FEE",
        "ADJUSTMENT",
        "ADJUST BAD DEBT"
    ])
]

print("Clearly non-product records:", len(non_product))

print("\nBreakdown:")
print(non_product["Description"].value_counts())

Clearly non-product records: 2579

Breakdown:
Description
POSTAGE            1252
DOTCOM POSTAGE      709
Manual              567
AMAZON FEE           34
adjustment           14
Adjustment            2
Adjust bad debt       1
Name: count, dtype: int64

In [34]:
# Remove clearly non-product transaction records

non_product_descriptions = [
    "POSTAGE",
    "DOTCOM POSTAGE",
    "MANUAL",
    "AMAZON FEE",
    "ADJUSTMENT",
    "ADJUST BAD DEBT"
]

clean_df = clean_df[
    ~clean_df["Description"].astype(str).str.upper().isin(non_product_descriptions)
].copy()

print("Rows after removing non-product transactions:", len(clean_df))

Rows after removing non-product transactions: 532724

In [35]:
# Remove records with missing product descriptions

clean_df = clean_df.dropna(subset=["Description"]).copy()

print("Final cleaned dataset rows:", len(clean_df))
print("Final cleaned dataset columns:", len(clean_df.columns))

print("\nRemaining missing values:")
print(clean_df.isnull().sum())

Final cleaned dataset rows: 532132
Final cleaned dataset columns: 8

Remaining missing values:
InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     132200
Country             0
dtype: int64

In [36]:
# Save the final cleaned dataset
output_file = "/content/Online_Retail_Cleaned.csv"

clean_df.to_csv(output_file, index=False)

print("Cleaned dataset saved successfully!")
print("File:", output_file)
print("Rows:", len(clean_df))
print("Columns:", len(clean_df.columns))

Cleaned dataset saved successfully!
File: /content/Online_Retail_Cleaned.csv
Rows: 532132
Columns: 8